version: '3.9'

x-kong-config: &kong-env
  KONG_DATABASE: postgres
  KONG_PASSWORD: kong
  KONG_PG_HOST: db
  KONG_PG_PASSWORD: kong

networks:
  kong-net:
    external: false

services:
  db:
    image: postgres:13
    networks:
      - kong-net
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
  migrations:
    image: kong/kong-gateway:3.3.1.0
    networks:
      - kong-net
    depends_on:
      - db
    command: kong migrations bootstrap
    environment:
      <<: *kong-env
  migrations-up:
    image: kong/kong-gateway:3.3.1.0
    networks:
      - kong-net
    depends_on:
      - db
    command: kong migrations up && kong migrations finish
    environment:
      <<: *kong-env
  kong_gateway:
    image: kong/kong-gateway:3.3.1.0
    networks:
      - kong-net
    depends_on:
      - db
    environment:
      <<: *kong-env
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_URL: http://localhost:8002
      KONG_LICENSE_DATA:
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
      - 8002:8002
      - 8445:8445
      - 8003:8003
      - 8004:8004
